package com.jbk.EProc.Vehicle.Bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;

import org.springframework.boot.context.properties.ConstructorBinding;

import lombok.Data;
import lombok.RequiredArgsConstructor;
import lombok.ToString;

// Generated Feb 22, 2020 3:00:43 PM by Hibernate Tools 5.2.12.Final

/**
 * Vehicles generated by hbm2java
 */

@Data
@RequiredArgsConstructor
@ToString

public class Vehicles implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	
	@NotNull(message = "vehicle No. cant be null")
	private String vehicleNo;
	private int loadedWt;
	private int maxLoad;

}
